### ISSUE TITLE
bootloader

### ISSUE THREAD

**Issue by BG7YWL** [ElectronicCats/NFC-Copy-Cat#1]
NFC Copy Cat is an interesting project. I made several PCBs. How can I burn the bootloader?

![微信图片_20200429161646](https://user-images.githubusercontent.com/9145406/80574830-252fa280-8a35-11ea-8143-7ad34791cd9e.jpg)

**Comment by sabas1080** [comment]
@K1two2 Hi, wow interesting, for burn bootloader you can use a SWD programmer as Jlink or Baclkmagic in J3

Binary available in https://github.com/ElectronicCats/Arduino_Boards_Index/tree/gh-pages/electroniccats/samd/bootloaders/nfc_copy_cat

**Comment by K1two2** [comment]
Thank you, sir ~
I have been trying to search for information about the uf2 bootloader, and it turns out that there are ready-made BIN firmware downloads in the Arduino Boards Index. 
hahaha~

**Comment by BG7YWL** [comment]
> @K1two2 Hi, wow interesting, for burn bootloader you can use a SWD programmer as Jlink or Baclkmagic in J3
> 
> Binary available in https://github.com/ElectronicCats/Arduino_Boards_Index/tree/gh-pages/electroniccats/samd/bootloaders/nfc_copy_cat

Thank you, sir ~
I have been trying to search for information about the uf2 bootloader, and it turns out that there are ready-made BIN firmware downloads in the Arduino Boards Index.
hahaha~

**Comment by sabas1080** [comment]
Oh when you compile UF2 generate various binaries https://github.com/ElectronicCats/uf2-samd21/tree/master/boards/nfc_copy_cat

**Comment by joelsernamoreno** [comment]
Hi!

The bootloader (binary) link does not exist. Where can I find it?

Thanks!

**Comment by sabas1080** [comment]
@joelsernamoreno binary file in our arduiino core https://github.com/ElectronicCats/ArduinoCore-samd/tree/master/bootloaders/nfc_copy_cat
