### ISSUE TITLE
Instructions to connect and setup 

### ISSUE THREAD

**Issue by jasonkirkb** [ElectronicCats/NFC-Copy-Cat#2]
It will be nice if the wiki page is updatd with the details to setup the connection of NFC Copy Cat with NFC Module for the Begineers and student like me to follow through the examples. Appriciate the samples in the repo.

**Comment by FelipeIslas** [comment]
Hi @jasonkirkb We have listened to you and our wiki page is updated !!! Now it is a little clearer and more understandable for beginners, I recommend you go through it to clarify your doubts... Happy hacking!
