### ISSUE TITLE
Hardware setup imformation

### ISSUE THREAD

**Issue by Pdubs19** [ElectronicCats/NFC-Copy-Cat#3]
Hey can you send some info on how to hook up and program the board with arduino mega 2560. Also any pictures and basic hardware/hookup support would be appreciated.

**Comment by sabas1080** [comment]
Can you explain a little more what you want to do? NFC copy cat uses a SAMD21

**Comment by Pdubs19** [comment]
Just want to be able to run the nfc read and be able to spoof magstripes.
So really the read replay spoof code. I'm new to programming circuit
boards. I have an arduino uno and mega. I'm just looking for a little more
info on how the board works. Do I just need to program the pn532 board and
connect it to the nfc copycat board. I got the nfc copycat into bootloader
mode but am not really sure how to program the nfc and magspoof buttons

**Comment by Pdubs19** [comment]
The samd21 mi

**Comment by Pdubs19** [comment]
I have the samd21 micro controller nfc copy cat 1.4v board with the electro
house nfc v3 board.

**Comment by sabas1080** [comment]
@Pdubs19 Have you already consulted our wiki?

https://github.com/ElectronicCats/NFC-Copy-Cat/wiki

**Comment by Pdubs19** [comment]
Yes. All I'm really wondering is if I need to program either the nfc
copycat samd21 board or the pn532 nxp board separately or if I only have to
program one of them and then connect the boards together. Ik this is a
newbie question but I really want to make this device work. Also does the
samd21 board coil connect to the nxp pn532 coil somehow for the read replay
spoof programming

**Comment by Pdubs19** [comment]
Don't want to waste anyone's time but anymore pictures and basic info on
how to start and which boards have to be programmed and what order etc.
would be greatly apprecisted.

**Comment by Pdubs19** [comment]
For Magpoof coil

#define L1 (14) //LED1

#define L2 (5) //LED2

#define L3 (4) //LED3

For Buttons

#define MPIN (28) //MagsSpoof Button

#define NPIN (27) //NFC Button

Does this mean I need to connect the LED 1 to 14 on the arduino?  If so what it's the connection for LED 1 on the nfc samd21 nfc board? Also what type of arduino is being used for these examples?

**Comment by FelipeIslas** [comment]
Hi @Pdubs19 
We are using our NFC Copy-Cat, which as you say has a SAMD21, this board has 3 onboard programmable LEDs and they are on pin 14, 4 and 5, so in the example these numbers are used for those LEDs.
Our Wiki was Updated, now it is a little clearer!!! I recommend you see it to clarify some of your doubts

**Comment by Pdubs19** [comment]
Yo thanks for the new wiki feels like Christmas has come early. I'm totally new to programming but couldn't resist buying the nfc copy cat once I read about it.
